- geoarrow-pandas/src/geoarrow/pandas/lib.py
- geoarrow-pandas/tests/test_geoarrow_pandas.py
- geoarrow-pandas/tests/test_geoarrow_pandas_geopandas.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/__init__.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/_compute.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/_scalar.py
- geoarrow-pyarrow/tests/test_geopandas.py
- geoarrow-pyarrow/tests/test_pyarrow.py
Wires up an interface (and leaves future PRs to handle integration with to/from ragged array).
For pandas integration:
```python
import geoarrow.pandas as _
import pandas as pd
df = pd.read_parquet("https://github.com/geoarrow/geoarrow-data/releases/download/latest-dev/ns-water-basin_point.parquet")
df.geometry.geoarrow.to_geopandas()
#> 0     POINT (277022.694 4820886.610)
#> 1     POINT (315701.255 4855051.379)
#> 2     POINT (255728.660 4851022.108)
#> 3     POINT (245206.784 4895609.410)
df.geometry[0].to_shapely()
#> POINT (277022.6936181751 4820886.609673489)
```
For pyarrow integration:
```python
array = ga.array(["POINT (30 10)"])
ga.to_geopandas(array)
#> 0    POINT (30.00000 10.00000)
#> dtype: geometry
array[0].to_shapely()
#> <POINT (30 10)>
```
> Wire up interface for to/from geopandas

- geoarrow-pyarrow/src/geoarrow/pyarrow/_array.py
- geoarrow-pyarrow/tests/test_compute.py
- geoarrow-pyarrow/tests/test_pyarrow.py
..the existing extension array methods were outdated and have been superceeded by `_compute` functions that work on more things than just an array. Because pyarrow's `ChunkedArray` does not have type-specific methods, I think we want to encourage (e.g.) `geoarrow.pyarrow.as_wkt(something)` rather than `something.as_wkt()` because it's pretty easy to get `something` that is a `ChunkedArray` (e.g., by using `__arrow_array__` protocol or `pyarrow.array()`, both of which might return either).
> chore: Remove outdated array methods

- geoarrow-pyarrow/src/geoarrow/pyarrow/_compute.py
- geoarrow-pyarrow/tests/test_compute.py
This was a half-baked part of the initial code that was never actually used. Concurrency should almost certainly be handled above (e.g., dask) or below (e.g., in geoarrow-c)...what ended up happening was that the tasks took so little time to complete that it didn't end up helping much.
> refactor: Remove threaded compute function options

- docs/source/pyarrow.rst
- geoarrow-pyarrow/pyproject.toml
- geoarrow-pyarrow/src/geoarrow/pyarrow/io.py
- geoarrow-pyarrow/tests/test_io.py
...lifted from https://github.com/geoarrow/geoarrow-data/blob/main/ogr_to_geoarrow.py that was used to make example data. This is useful because you can get pretty much *any* data as geoarrow with pretty minimal code. It can be faster than reading through GeoPandas (but that's not the primary motivation):
```python
from geoarrow.pyarrow import io
tab = io.read_pyogrio_table("https://raw.githubusercontent.com/geoarrow/geoarrow-data/v0.1.0/example/example-linestring.gpkg")
tab.column("geom").chunk(0).geobuffers()
#> [None,
#>  array([0, 3, 3, 3], dtype=int32),
#>  array([30., 10., 40.]),
#>  array([10., 30., 40.])]
```
> feat: Add `read_pyogrio_table()`

- geoarrow-pyarrow/src/geoarrow/pyarrow/_array.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/_compute.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/_kernel.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/_type.py
- geoarrow-pyarrow/tests/test_pyarrow.py
This resulted in some unexpected performance characteristics and was not all that useful (since you could still have geometrically invalid data that happened to parse with `validate=True`). Because it was the default, it was pretty easy to get terrible performance and not know why (e.g., with `geoarrow.pyarrow.io.read_pyogrio_table()`).
> perf: Remove validation from `wrap_array()`

- docs/source/pyarrow.rst
- geoarrow-pandas/src/geoarrow/pandas/lib.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/__init__.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/_array.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/_compute.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/_kernel.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/_scalar.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/_type.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/dataset.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/io.py
- geoarrow-pyarrow/tests/test_pyarrow.py
...before anybody actually uses this!
Unfortunately, `GeometryType` is a no go because it's the enum name. It's a base class, so hopefully not an issue that it's more verbose.
> Rename `VectorType` to `GeometryExtensionType`

- geoarrow-metapackage/README.md
- geoarrow-metapackage/pyproject.toml
This is a metapackage for the `geoarrow` namespace on PyPI. [Native namespace packages](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages) are _implicit_ upon the fact that there is no `__init__.py` at the top level of a folder. So if `geoarrow.pyarrow` publishes a wheel with `geoarrow/pyarrow/__init__.py` but another package `geoarrow` publishes a wheel with `geoarrow/__init__.py`, then `geoarrow.pyarrow` will never be able to be imported because the latter will shadow the former.
This metapackage prevents someone else from taking the "geoarrow" name on PyPI, which lessens the chance that someone else will publish a Python package that exports `geoarrow/__init__.py`.
You can build the Python module with
```
pip install -U build
python …
```
> geoarrow python metapackage

- geoarrow-pandas/src/geoarrow/pandas/lib.py
- geoarrow-pandas/tests/test_geoarrow_pandas.py
Credit to @martinfleis for the epic traceback that highlighted this and @jorisvandenbossche for the `concat_arrays()` trick!
```python
import geoarrow.pandas as gapd
import numpy as np
pts_array = ga.point().from_geobuffers(
None, np.random.random(int(1e6)), np.random.random(int(1e6))
)
pts_pd = gapd.GeoArrowExtensionArray(pts_array)
%timeit pts_pd.copy()
#> Before this PR:
#> 37.8 s ± 188 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
#> After this PR:
#> 630 µs ± 22.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```
> perf: Optimize pandas `GeoArrowExtensionArray.copy()`

- geoarrow-pyarrow/src/geoarrow/pyarrow/io.py
- geoarrow-pyarrow/tests/test_io.py
As a follow-up to #34!
geography column support for "compatible" Parquet files:
```python
from geoarrow.pyarrow import io
import pyarrow as pa
from pyarrow import parquet
table = pa.table([pa.array(["LINESTIRNG (0 0, 1 1)"])], ["geography"])
parquet.write_table(table, "test.parquet")
table_out = io.read_geoparquet_table("test.parquet")
table_out["geography"].type
#> WktType(spherical geoarrow.wkt <PROJJSON:{"$schema": "[https://proj...>](https://proj...%3E/))
```
geography_names behaviour:
```python
from geoarrow.pyarrow import io
import pyarrow as pa
from pyarrow import parquet
table = pa.table([ga.as_geoarrow(["LINESTRING (0 0, 1 1)"])], ["geometry"])
io.write_geoparquet_table(table, "test.parquet")
parquet.read_schema("test.parquet").metadata[b"geo"]
#> …
```
> fix(geoarrow-pyarrow): Better geometry_names, geography column support, and default geometry column name

- geoarrow-pandas/src/geoarrow/pandas/lib.py
- geoarrow-pyarrow/pyproject.toml
- geoarrow-pyarrow/src/geoarrow/pyarrow/_array.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/_compute.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/_kernel.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/_scalar.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/_type.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/dataset.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/io.py
Ensures that `pyarrow_hotfix` is imported everywhere we import pyarrow.
> fix: Use pyarrow_hotfix everywhere

- .github/workflows/test.yaml
- geoarrow-pandas/pyproject.toml
- geoarrow-pyarrow/pyproject.toml
- geoarrow-pyarrow/src/geoarrow/pyarrow/_compute.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/io.py
- geoarrow-pyarrow/tests/test_io.py
```python
from geoarrow.pyarrow import io
from pyarrow import parquet
points_tbl = io.read_pyogrio_table(
"https://github.com/geoarrow/geoarrow-data/releases/download/v0.1.0/ns-water-water_junc.fgb.zip",
columns=["geometry"],
)
points_tbl = points_tbl.set_column(
0, "geometry", ga.make_point(*ga.point_coords(points_tbl["geometry"]))
)
def read_and_do_something_with_values(f):
tbl = io.read_geoparquet_table(f)
ga.box_agg(tbl["geometry"])
io.write_geoparquet_table(points_tbl, "test.parquet", geometry_encoding="WKB")
%timeit read_and_do_something_with_values("test.parquet")
#> 10.6 ms ± 87.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
io.write_geoparquet_table(
points_tbl,
"test.parquet",
geometry_encoding=io.geoparquet_encoding_geoarrow()
)
%timeit …
```
> feat(geoarrow-pyarrow): Implement single-geometry encodings for geoparquet writer

- geoarrow-pyarrow/src/geoarrow/pyarrow/io.py
Now that pyogrio opportunistically returns GeoArrow extension types, we can avoid creating them in most cases! This was causing existing tests to fail.
> fix(geoarrow-pyarrow): Fix `read_pyogrio_table()` for newer pyogrio

- geoarrow-types/src/geoarrow/types/constants.py
- geoarrow-types/src/geoarrow/types/type_pyarrow.py
- geoarrow-types/src/geoarrow/types/type_spec.py
- geoarrow-types/tests/test_type_pyarrow.py
- geoarrow-types/tests/test_type_spec.py
```python
import geoarrow.types as gt
extension_type = gt.wkb(crs=gt.OGC_CRS84).to_pyarrow()
extension_type.storage_type
#> DataType(binary)
extension_type.crs
#> ProjJsonCrs(OGC:CRS84)
extension_type.to_pandas_dtype()
#> extension<geoarrow.wkb<WkbType>>[pyarrow]
extension_type = gt.point(dimensions="xyz", coord_type="interleaved").to_pyarrow()
extension_type.storage_type
#> FixedSizeListType(fixed_size_list<xyz: double not null>[3])
```
> feat(geoarrow-types): pyarrow geometry extension type implementation

- .github/workflows/docs.yaml
- .github/workflows/test.yaml
- .gitignore
- geoarrow-pandas/pyproject.toml
- geoarrow-pandas/src/geoarrow/pandas/__init__.py
- geoarrow-pandas/tests/test_geoarrow_pandas.py
- geoarrow-pyarrow/pyproject.toml
- geoarrow-pyarrow/src/geoarrow/pyarrow/__init__.py
- geoarrow-pyarrow/tests/test_pyarrow.py
- geoarrow-types/pyproject.toml
- geoarrow-types/src/geoarrow/types/__init__.py
- geoarrow-types/tests/test_package.py
This PR updates the setuptools_scm versioning on the three relevant packages to use a package-specific tag format (such that we can release only one of them at a time). It also adds a `__version__` member to the namespace to make it easier to do runtime version checking.
> refactor(geoarrow-pandas,geoarrow-pyarrow): Use package-specific setup for setuptools_scm

- geoarrow-pandas/tests/test_geoarrow_pandas.py
- geoarrow-pyarrow/tests/test_compute.py
- geoarrow-pyarrow/tests/test_pyarrow.py
- geoarrow-types/src/geoarrow/types/crs.py
- geoarrow-types/src/geoarrow/types/type_spec.py
- geoarrow-types/tests/test_crs.py
- geoarrow-types/tests/test_type_spec.py
This PR implements CRS values that are not JSON objects in the extension metadata (while preserving the PROJJSON-ness of CRSes that are declared in this way). It also improves interoperability with pyproj by adding the .to_wkt() attribute on the ProjJsonCrs and the StringCrs (since pyproj uses this internally to construct CRSes from arbitrary objects).
> feat(geoarrow-types): Implement non-PROJJSON crses and crs_type metadata

- geoarrow-pyarrow/src/geoarrow/pyarrow/_compute.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/_type.py
- geoarrow-types/src/geoarrow/types/type_pyarrow.py
- geoarrow-types/src/geoarrow/types/type_spec.py
- geoarrow-types/tests/test_type_pyarrow.py
It's a monster of a union, but it does work:
```python
import geoarrow.types as gt
ga.extension_type(gt.type_spec(gt.Encoding.GEOARROW, gt.GeometryType.GEOMETRY))
#> GeometryUnionType(geoarrow.geometry)
```
This PR adds enough support such that pyarrow should be able to import and export a geometry array produced by geoarrow-rs, and enough support that people can experiment with the type if they want to (but I'll leave other functionality up to future PRs 🙂 ).
> feat(geoarrow-types): Add support for geometry/collection union

- .github/workflows/test.yaml
- geoarrow-types/pyproject.toml
- geoarrow-types/src/geoarrow/types/crs.py
- geoarrow-types/tests/test_type_pyarrow.py
This PR tests geoarrow-types against older Python versions. The tests already passed for Python 3.8, and with minimal changes we can support 3.7. Python 3.7 is the version of Python available on some hosted runtimes and is the minimum supported version for Sedona (which mostly just makes configuring their CI hard if we don't support Python 3.7).
> chore(geoarrow-types): Test against Python 3.7 and Python 3.8

- geoarrow-pyarrow/src/geoarrow/pyarrow/_compute.py
- geoarrow-pyarrow/tests/test_geopandas.py
This PR supports table-like objects in `to_geopandas()`, ensuring that we use GeoPandas' methods first and fall back on our own if GeoPandas fails (because it's an old version or because it doesn't support the type in question).
```python
import pyarrow as pa
table = pa.table({"geometry":  ga.as_geoarrow(["POINT (0 1)"])})
ga.to_geopandas(table)
```
Closes #18.
> feat(geoarrow-pyarrow): Support table-like objects in `to_geopandas()`

- geoarrow-pandas/src/geoarrow/pandas/lib.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/_array.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/_compute.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/_kernel.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/_scalar.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/dataset.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/io.py
- geoarrow-pyarrow/tests/test_pyarrow.py
- geoarrow-types/src/geoarrow/types/crs.py
- geoarrow-types/src/geoarrow/types/type_spec.py
A future version of geoarrow-pyarrow will probably further reduce the dependency on geoarrow-c and/or mandate >- 0.2; however, for the time being this makes it easier for all the CI to hum happily along.
> fix: Enable build against geoarrow-c 0.2

- .github/workflows/test.yaml
- geoarrow-pandas/src/geoarrow/pandas/lib.py
- geoarrow-pyarrow/pyproject.toml
- geoarrow-pyarrow/src/geoarrow/pyarrow/_array.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/_compute.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/_kernel.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/_scalar.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/_type.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/dataset.py
- geoarrow-pyarrow/src/geoarrow/pyarrow/io.py
The hotfix will break in the forthcoming pyarrow attempting to unregister an extension type that no longer exists!
> chore(geoarrow-pyarrow): Remove pyarrow_hotfix and set minimum version

- geoarrow-pyarrow/src/geoarrow/pyarrow/_compute.py
- geoarrow-types/src/geoarrow/types/constants.py
- geoarrow-types/src/geoarrow/types/type_spec.py
- geoarrow-types/tests/test_type_spec.py
Adds support for other edge types to the Python bindings
> feat(geoarrow-types): Add support for GeoArrow 0.2 edge types

- .github/workflows/test.yaml
- README.ipynb
- README.md
I think coverage was excluding geoarrow-types because of something with setuptools_scm.
README was also very out of date!
> chore: Update README and coverage action to include tags

- geoarrow-pandas/tests/test_geoarrow_pandas_suite.py
geoarrow-pandas isn't referenced anymore after geoarrow.pyarrow 0.3 and could/should probably be removed; however, this is a less invasive change than removing the whole package just to keep CI on the go.
> chore(geoarrow-pandas): Skip failing interface test
